docsPath: ./myapp-docs
structure:
  summary: toc.md
  assets: assets
  docTreeOptions:
    openApiTryIt: false
    showDownloadOpenApiFile: false
    shouldCreateSchemaCategory: false
    shouldCreateIntro: false
    openApiLanguageExamples:
      - value: javascript
        label: js
      - value: go
        label: go
footerTemplate: ""
headerIncludes: ""
